import assert from "node:assert/strict";
import test from "node:test";

test("v0.8.15 invitation removes combined pages and repeats a non-scrolling return gesture", async () => {
  const { readFile } = await import("node:fs/promises");
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(source, /scroll-pages/);
  assert.match(source, /story-page story-page-1/);
  assert.doesNotMatch(source, /story-page story-page-4/);
  assert.match(source, /IntersectionObserver/);
  assert.match(source, /scrollIntoView/);
  assert.match(source, /DogRibbon/);
  assert.match(source, /dog-ribbon-guide\.png/);
  assert.match(source, /黃金獵犬與長毛臘腸/);
  assert.match(source, /families-cover\.jpg/);
  assert.match(source, /families-detail\.jpg/);
  assert.match(source, /2026-12-12T18:00:00\+08:00/);
  assert.match(source, /黃春安、謝秀鳳/);
  assert.match(source, /李文獎、黃意芬/);
  assert.match(source, /台南晶英酒店/);
  assert.match(source, /從指尖的滑過　到餘生的相握/);
  assert.match(source, /從一次不經意的相遇開始/);
  assert.match(source, /visualViewport/);
  assert.match(source, /landscapeTipOpen/);
  assert.match(source, /向右拖拉或點擊雙犬即可展開/);
  assert.match(source, /台南晶英酒店・大成廳/);
  assert.match(source, /silks-place-logo\.png/);
  assert.match(source, /silks-traffic-guide\.png/);
  assert.match(source, /silks-hotel-exterior\.png/);
  assert.match(source, /點擊查看詳細交通資訊/);
  assert.match(source, /selectedTransport/);
  assert.match(source, /高鐵快捷公車/);
  assert.match(source, /B5－B7/);
  assert.match(source, /className="xi-stamp" aria-hidden="true" \/>/);
  assert.match(source, /className="venue-logo-mark"/);
  assert.match(source, /className="venue-hotel-row"/);
  assert.doesNotMatch(source, /venue-logo-card/);
  assert.doesNotMatch(source, /short: "出席回覆"/);
  assert.match(source, /viewport\.scale > 1\.01/);
  assert.match(source, /COUNTDOWN <span>TO WEDDING/);
  assert.doesNotMatch(source, /mobile-scroll-cue/);
  assert.match(source, /transport-\$\{option\.id\}\.png/);
  assert.match(source, /transport-drive-clean\.png/);
  assert.doesNotMatch(source, /transport-parking-clean\.png/);
  assert.match(source, /className="parking-symbol">P/);
  assert.doesNotMatch(source, /family-combined-page/);
  assert.doesNotMatch(source, /venue-combined-page/);
  assert.doesNotMatch(source, /婚宴資訊合併預覽/);
  assert.doesNotMatch(source, /地點與交通資訊合併預覽/);
  assert.doesNotMatch(source, /className="name-ornament"/);
  assert.match(source, /https:\/\/tainan\.silksplace\.com\/tw\//);
  assert.match(source, /}, 1000\);/);
  assert.match(source, /setTimeout/);
  assert.match(source, /slowScrollTo/);
  assert.match(source, /duration = 1800/);
  assert.match(source, /SwipeGesture/);
  assert.match(source, /swipe-hand\.png/);
  assert.match(source, /swipeGuideMode/);
  assert.match(source, /setSwipeGuideMode\("down"\)/);
  assert.match(source, /}, 3000\);/);
  assert.match(source, /scrollTop < scrollRef\.current\.clientHeight \* \.8/);
  assert.match(source, /Math\.cos\(Math\.PI \* progress\)/);
  assert.doesNotMatch(source, /<p className="venue-time">/);
  assert.doesNotMatch(source, />第一章</);
  assert.doesNotMatch(source, />第二章</);
  assert.doesNotMatch(source, /PULL THE RIBBON TO OPEN/);
  assert.doesNotMatch(source, /pull-nav/);
  assert.doesNotMatch(source, /pull-handle/);
  assert.doesNotMatch(source, /invitation-canvas/);
  assert.doesNotMatch(source, /requestFullscreen/);

  assert.match(styles, /scroll-snap-type: y mandatory/);
  assert.match(styles, /scroll-snap-align: start/);
  assert.match(styles, /family-paper-card/);
  assert.match(styles, /dog-ribbon-opener/);
  assert.match(styles, /dog-ribbon-opener::before/);
  assert.match(styles, /--ribbon-opacity/);
  assert.match(styles, /portrait-view-tip/);
  assert.match(styles, /family-title-row/);
  assert.match(styles, /venue-opening/);
  assert.match(styles, /venue-light-run/);
  assert.match(styles, /transport-tabs/);
  assert.match(styles, /transport-slide-in/);
  assert.match(styles, /mix-blend-mode: multiply/);
  assert.match(styles, /\.venue-map-panel,\s*\.transport-panel/);
  assert.match(styles, /clip-path: polygon\(0 0, 100% 0, 78% 100%, 0 100%\)/);
  assert.match(styles, /dog-chevron-flow/);
  assert.match(styles, /about-page-preview\.is-active/);
  assert.match(styles, /transport-icon-parking/);
  assert.match(styles, /parking-symbol/);
  assert.match(styles, /transport-icon-rail img/);
  assert.match(styles, /width: 150%/);
  assert.match(styles, /height: clamp\(230px, 28vh, 292px\)/);
  assert.match(styles, /width: 216%/);
  assert.match(styles, /right: max\(21px, env\(safe-area-inset-right\)\)/);
  assert.match(styles, /top: max\(19px, env\(safe-area-inset-top\)\)/);
  assert.match(styles, /width: 237%/);
  assert.match(styles, /height: 122%/);
  assert.match(styles, /width: 120%/);
  assert.match(styles, /height: calc\(100% - 52px\)/);
  assert.match(styles, /border: 1px solid #8f999c/);
  assert.match(styles, /transform: translate\(-50%, -50%\)/);
  assert.match(styles, /align-self: start/);
  assert.match(styles, /mix-blend-mode: multiply/);
  assert.match(styles, /\.story-page \{\s*height: 100%;\s*min-height: 100%/);
  assert.match(styles, /mix-blend-mode: normal/);
  assert.match(styles, /\.transport-icon-rail::after/);
  assert.match(styles, /border-color: #f6a064/);
  assert.match(styles, /border-color: #995daf/);
  assert.match(styles, /\.swipe-gesture\.is-visible/);
  assert.match(styles, /mobile-swipe-guide-up 1800ms/);
  assert.match(styles, /mobile-swipe-guide-down 1400ms/);
  assert.match(styles, /cubic-bezier\(\.45,0,\.25,1\) 2/);
  assert.match(styles, /translateY\(-30vh\)/);
  assert.match(styles, /translateY\(-28vh\)/);
  assert.match(styles, /hotel-website/);
  assert.match(styles, /venue-trigger-shine/);
  assert.match(styles, /text-size-adjust: 100%/);
  assert.match(styles, /scaleX\(-1\)/);
  assert.match(styles, /scroll-snap-type: y mandatory/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
